// Post-build: generate out/sw.js with a precache manifest of every exported file.
// Strategy: precache the app shell + all static assets so core gameplay works offline
// after the first visit. Navigations: network-first with cached fallback.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const OUT = "out";
const files = [];
function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else files.push(p);
  }
}
walk(OUT);
const hash = createHash("sha256");
const urls = [];
for (const f of files) {
  const rel = "/" + relative(OUT, f).split(sep).join("/");
  if (rel === "/sw.js" || rel.endsWith(".map") || (rel.endsWith(".txt") && !rel.includes("_next"))) continue;
  // Flag SVGs (500+) are cached at runtime when first shown rather than precached.
  if (rel.startsWith("/_next/static/media/") && rel.endsWith(".svg")) continue;
  hash.update(rel).update(readFileSync(f));
  urls.push(rel.endsWith("/index.html") ? rel.slice(0, -"index.html".length) : rel);
}
const version = hash.digest("hex").slice(0, 12);
const sw = `/* Pitchborn service worker — generated by scripts/pwa/build-sw.mjs */
const VERSION = ${JSON.stringify(version)};
const CACHE = "pitchborn-" + VERSION;
const PRECACHE = ${JSON.stringify(urls)};

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Add in small batches so one failure doesn't abort the install.
    for (let i = 0; i < PRECACHE.length; i += 20) {
      await Promise.all(PRECACHE.slice(i, i + 20).map((u) => cache.add(u).catch(() => undefined)));
    }
    self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key.startsWith("pitchborn-") && key !== CACHE) await caches.delete(key);
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // never touch third-party (ads) requests
  if (req.mode === "navigate") {
    event.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const cache = await caches.open(CACHE);
        cache.put(req, fresh.clone());
        return fresh;
      } catch {
        const cache = await caches.open(CACHE);
        const path = url.pathname.endsWith("/") ? url.pathname : url.pathname + "/";
        return (await cache.match(req)) || (await cache.match(path)) || (await cache.match("/play/")) || (await cache.match("/")) || Response.error();
      }
    })());
    return;
  }
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: url.pathname.startsWith("/_next/static/") });
    if (hit) return hit;
    try {
      const res = await fetch(req);
      if (res.ok && (url.pathname.startsWith("/_next/") || /\\.(png|webp|svg|woff2?|css|js)$/.test(url.pathname))) cache.put(req, res.clone());
      return res;
    } catch {
      return hit || Response.error();
    }
  })());
});
`;
writeFileSync(join(OUT, "sw.js"), sw);
console.log(`sw.js generated: ${urls.length} files precached (version ${version})`);
