/**
 * Regenerates the art production lists from the code, so they never drift:
 *   docs/portrait-art/HAIRSTYLES.md  the 100-style target library
 *   docs/portrait-art/POC_ASSETS.md  every file the first art test needs, with delivery status
 *
 *   npm run portraits:docs
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { MANIFEST } from "../../src/components/art/illustrated/select";
import { SLOTS } from "../../src/components/art/illustrated/slots";
import { HAIRSTYLES, RARITY_SHARE } from "../../src/engine/appearance/hairstyles";

mkdirSync("docs/portrait-art", { recursive: true });

const head = "| # | Name | id | Category | Texture | Rarity | Era | Layers | Art | Structure |\n|---|---|---|---|---|---|---|---|---|---|";
const rows = HAIRSTYLES.map((h, i) => {
  const layers = h.preset ? `uses \`${h.preset.art}\`${h.preset.color ? ` in ${h.preset.color}` : ""}${h.preset.secondary ? `, ${h.preset.secondary} secondary` : ""}` : [h.hasBackLayer ? "front + back" : "front", h.hasSecondaryColor ? "secondary mask" : "", h.defaultAccessory ? `+ ${h.defaultAccessory}` : ""].filter(Boolean).join(", ");
  return `| ${i + 1} | ${h.name} | \`${h.id}\` | ${h.category} | ${h.texture} | ${h.rarity} | ${h.era ?? ""} | ${layers} | ${h.status} | ${h.brief.replace(/\|/g, "/")} |`;
});
writeFileSync(
  "docs/portrait-art/HAIRSTYLES.md",
  `# Hairstyle library (target: 100)\n\nGenerated by \`npm run portraits:docs\` from \`src/engine/appearance/hairstyles.ts\`. Do not edit by hand.\n\nArt status: **slot** = folder and brief ready, art not delivered; **planned** = later; **ready** = delivered and approved.\nGeneration shares per rarity tier: ${Object.entries(RARITY_SHARE).map(([r, s]) => `${r} ${Math.round(s * 100)}%`).join(", ")} (split across the tier, then leaned by age, era and skin tone).\nNames are fictional and descriptive; styles may evoke football eras but never a real person.\n\n${head}\n${rows.join("\n")}\n`,
);

const poc = SLOTS.filter((s) => s.poc);
const list = poc
  .map((s) => {
    const files = s.roles.map((r) => `  - [${MANIFEST[`${s.path}/${r}`] ? "x" : " "}] \`art/portrait/source/${s.path}/${r}.png\``).join("\n");
    const opt = s.optional?.length ? `\n  - optional: ${s.optional.map((r) => `\`${r}.png\``).join(", ")}` : "";
    const tint = s.tint && Object.keys(s.tint).length ? ` (colour: ${Object.entries(s.tint).map(([r, t]) => `${r} takes ${t}`).join(", ")})` : "";
    return `- **${s.path}**${tint}, area x ${s.region[0]} y ${s.region[1]} w ${s.region[2]} h ${s.region[3]}\n${files}${opt}`;
  })
  .join("\n");
const total = poc.reduce((n, s) => n + s.roles.length, 0);
const done = poc.reduce((n, s) => n + s.roles.filter((r) => MANIFEST[`${s.path}/${r}`]).length, 0);
writeFileSync(
  "docs/portrait-art/POC_ASSETS.md",
  `# First art test: asset checklist\n\nGenerated by \`npm run portraits:docs\`. ${done} of ${total} required layer files delivered.\n\nEvery file is a 512 x 512 transparent PNG drawn in place over \`art/portrait/guides/canvas-guide.png\`. See docs/PORTRAIT_ART.md for what each layer role means.\n\n${list}\n`,
);
console.log(`wrote docs/portrait-art/HAIRSTYLES.md and POC_ASSETS.md (${done}/${total} POC files delivered)`);
